In [60]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score,recall_score,accuracy_score,precision_score,confusion_matrix,classification_report
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import seaborn as sns
import pandas as pd
from urllib.parse import urlparse
import mlflow
import pandas as pd
import plotly.express as px

In [62]:
df = pd.read_csv(r'data/column_3C.dat', sep = ' ', header=None)
#df.to_csv(r'data/raw/data.csv')

In [55]:
df.iloc[[0]]

0      1      2      3      4     5   6
0  63.03  22.55  39.61  40.48  98.67 -0.25  DH

In [56]:
print(df.describe())

                0           1           2           3           4           5
count  310.000000  310.000000  310.000000  310.000000  310.000000  310.000000
mean    60.496484   17.542903   51.930710   42.953871  117.920548   26.296742
std     17.236109   10.008140   18.553766   13.422748   13.317629   37.558883
min     26.150000   -6.550000   14.000000   13.370000   70.080000  -11.060000
25%     46.432500   10.667500   37.000000   33.347500  110.710000    1.600000
50%     58.690000   16.360000   49.565000   42.405000  118.265000   11.765000
75%     72.880000   22.120000   63.000000   52.692500  125.467500   41.285000
max    129.830000   49.430000  125.740000  121.430000  163.070000  418.540000


In [59]:
print(y)

0      DH
1      DH
2      DH
3      DH
4      DH
       ..
305    NO
306    NO
307    NO
308    NO
309    NO
Name: 6, Length: 310, dtype: object


In [94]:
import requests, zipfile, io
import os 
#url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00212/

#file_name = 'vertebral_column_data.zip'


zip_file_url = url + file_name
r = requests.get(zip_file_url)
z = zipfile.ZipFile(io.BytesIO(r.content))
z = z.extract('column_3C.dat')
df = pd.read_csv('column_3C.dat', header= None, sep = ' ')
os.remove('column_3C.dat')

In [95]:
print(df)

         0      1      2      3       4      5   6
0    63.03  22.55  39.61  40.48   98.67  -0.25  DH
1    39.06  10.06  25.02  29.00  114.41   4.56  DH
2    68.83  22.22  50.09  46.61  105.99  -3.53  DH
3    69.30  24.65  44.31  44.64  101.87  11.21  DH
4    49.71   9.65  28.32  40.06  108.17   7.92  DH
..     ...    ...    ...    ...     ...    ...  ..
305  47.90  13.62  36.00  34.29  117.45  -4.25  NO
306  53.94  20.72  29.22  33.22  114.37  -0.42  NO
307  61.45  22.69  46.17  38.75  125.67  -2.71  NO
308  45.25   8.69  41.58  36.56  118.55   0.21  NO
309  33.84   5.07  36.64  28.77  123.95  -0.20  NO

[310 rows x 7 columns]


In [ ]:
# store feature matrix in "X"
X = df.loc[:,[0,1,2,3,4,5]]

# store response vector in "y"
y = df.loc[:,6]

print(X.shape)
print(y.shape)

for i in ["DH","SL","NO"]:
    print("classe : %s, nb exemplaires: %s" % (i, len(y[ y == i]) ) )
    


(310, 6)
(310,)
classe : DH, nb exemplaires: 60
classe : SL, nb exemplaires: 150
classe : NO, nb exemplaires: 100


In [ ]:
fig = px.scatter(df, x=0, y=5, color=6)
fig.show()


In [ ]:
fig = px.scatter_matrix(df,color=6)
fig.show()

In [97]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=111, shuffle=True) # 70% training and 30% test
"""
df_train = X_train.merge(y_train,how='inner', left_index=True, right_index=True)
df_train.to_csv(r'data/processed/vetebre_train.csv')

df_test = X_test.merge(y_test,how='inner', left_index=True, right_index=True)
df_test.to_csv(r'data/processed/vetebre_test.csv')
"""

"\ndf_train = X_train.merge(y_train,how='inner', left_index=True, right_index=True)\ndf_train.to_csv(r'data/processed/vetebre_train.csv')\n\ndf_test = X_test.merge(y_test,how='inner', left_index=True, right_index=True)\ndf_test.to_csv(r'data/processed/vetebre_test.csv')\n"

In [ ]:
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [ ]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8602150537634409


In [ ]:
def accuracymeasures(y_test,predictions,avg_method):
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average=avg_method)
    recall = recall_score(y_test, predictions, average=avg_method)
    f1score = f1_score(y_test, predictions, average=avg_method)
    target_names = ['0','1','2']
    print("Classification report")
    print("---------------------","\n")
    print(classification_report(y_test, predictions,target_names=target_names),"\n")
    print("Confusion Matrix")
    print("---------------------","\n")
    print(confusion_matrix(y_test, predictions),"\n")

    print("Accuracy Measures")
    print("---------------------","\n")
    print("Accuracy: ", accuracy)
    print("Precision: ", precision)
    print("Recall: ", recall)
    print("F1 Score: ", f1score)
    
    return accuracy,precision,recall,f1score

In [ ]:
max_depth = 5
n_estimators = 5

n_neighbors = 5


remote_server_uri = 'http://localhost:1234'

mlflow.set_tracking_uri(remote_server_uri)
mlflow.set_experiment('vetebre')

with mlflow.start_run(run_name='knn') as mlops_run:
    #model = RandomForestClassifier(max_depth=max_depth,n_estimators=n_estimators)
    model = KNeighborsClassifier(n_neighbors=n_neighbors)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy,precision,recall,f1score = accuracymeasures(y_test,y_pred,'weighted')

    #mlflow.log_param("max_depth",max_depth)
    #mlflow.log_param("n_estimators", n_estimators)
    mlflow.log_param("n_neighbors", n_neighbors)

    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("precision", precision)
    mlflow.log_metric("recall", recall)
    mlflow.log_metric("f1_score", f1score)

    tracking_url_type_store = urlparse(mlflow.get_artifact_uri()).scheme

    if tracking_url_type_store != "file":
        mlflow.sklearn.log_model(
            model, 
            "model", 
            registered_model_name='knn_model')
    else:
        mlflow.sklearn.load_model(model, "model")

2022/05/31 14:51:34 INFO mlflow.tracking.fluent: Experiment with name 'vetebre' does not exist. Creating a new experiment.


Classification report
--------------------- 

              precision    recall  f1-score   support

           0       0.62      0.71      0.67        14
           1       0.85      0.83      0.84        35
           2       0.98      0.95      0.97        44

    accuracy                           0.87        93
   macro avg       0.82      0.83      0.82        93
weighted avg       0.88      0.87      0.87        93
 

Confusion Matrix
--------------------- 

[[10  4  0]
 [ 5 29  1]
 [ 1  1 42]] 

Accuracy Measures
--------------------- 

Accuracy:  0.8709677419354839
Precision:  0.8772009178765279
Recall:  0.8709677419354839
F1 Score:  0.8735094818182307


Registered model 'knn_model' already exists. Creating a new version of this model...
2022/05/31 14:51:36 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: knn_model, version 3
Created version '3' of model 'knn_model'.
